apiVersion: v1
kind: Service
metadata:
  name: omp-service
spec:
  selector:
    app: jogodavida-omp
  ports:
    - protocol: TCP
      port: 8082 
      targetPort: 8080  # A porta onde o OpenMP está rodando no container
