apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogodavida-mpi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jogodavida-mpi
  template:
    metadata:
      labels:
        app: jogodavida-mpi
    spec:
      containers:
      - name: jogodavida-mpi
        image: karlacsf/jogodavida:latest
        command: ["mpirun", "--allow-run-as-root", "--oversubscribe", "-np", "4", "./MPI/jogodavidampi"]
        env:
        - name: OMPI_ALLOW_RUN_AS_ROOT
          value: "1"
        - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
