apiVersion: apps/v1
kind: Deployment
metadata:
  name: jogodavida-mpi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jogodavida-mpi
  template:
    metadata:
      labels:
        app: jogodavida-mpi
    spec:
      containers:
      - name: jogodavida-mpi
        image: carlacangussu/jogodavida:latest
        command: ["mpirun", "--allow-run-as-root", "--oversubscribe", "-np", "4", "./MPI/jogodavidampi"]
        env:
        - name: OMPI_ALLOW_RUN_AS_ROOT
          value: "1"
        - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
          value: "1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      - name: metrics-server
        image: k8s.gcr.io/metrics-server/metrics-server:v0.3.7
        args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
