apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - name: socket-server
        image: karlacsf/socket-server:latest 
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
